name: Deploy Staging 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login ke Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Jalankan Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          debug: true
          script: |
            # Cek apakah path staging sudah ada
            if [ -d "${{ vars.APP_STG_PATH }}" ]; then
              cd ${{ vars.APP_STG_PATH }}
              sudo docker compose down pacmusic-stg
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} ${{ vars.APP_STG_PATH }}
              cd ${{ vars.APP_STG_PATH }}
            fi

            # Generate file .env
            echo "APP_STG_PORT=${{ secrets.APP_STG_PORT }}" > .env
            echo "MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}" >> .env
            echo "MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}" >> .env
            echo "MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}" >> .env

            # Jalankan aplikasi dengan Docker
            sudo docker compose up --build --detach pacmusic-stg

      - name: Test Hit Endpoint
        run: |
          sleep 10
          curl "${{ secrets.STG_URL }}"
