name: Deploy Staging 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub (Opsional)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            # Check if APP_STG_PATH exists
            if [ -d "${{ vars.APP_STG_PATH }}" ]; then
              cd ${{ vars.APP_STG_PATH }}
              sudo docker compose down pacmusic-stg
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} ${{ vars.APP_STG_PATH }}
              cd ${{ vars.APP_STG_PATH }}
            fi
            
            # Generate .env file
            cat <<EOF > .env
            APP_STG_PORT=${{ secrets.APP_STG_PORT }}
            MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}
            MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}
            MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}
            EOF
            
            # Build dan deploy ulang container dengan benar
            sudo docker compose build pacmusic-stg
            sudo docker compose up --detach --force-recreate pacmusic-stg

      - name: Test Deployment
        run: |
          sleep 10
          curl ${{ secrets.STG_URL }}
