name: Deploy Staging 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up SSH and Execute Deployment Command
        uses: appleboy/ssh-action@master
        env: 
          APP_STG_PATH: ${{ vars.APP_STG_PATH }}
          GIT_URL: ${{ secrets.GIT_URL }}
          APP_STG_PORT: ${{ secrets.APP_STG_PORT }}
          MINIO_STG_ENDPOINT: ${{ secrets.MINIO_STG_ENDPOINT }}
          MINIO_STG_ACCESS_KEY: ${{ secrets.MINIO_STG_ACCESS_KEY }}
          MINIO_STG_SECRET_KEY: ${{ secrets.MINIO_STG_SECRET_KEY }}

        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          envs: APP_STG_PATH, GIT_URL, APP_STG_PORT, MINIO_STG_ENDPOINT, MINIO_STG_ACCESS_KEY, MINIO_STG_SECRET_KEY
          script: |

            # Check if APP_STG_PATH exists
            if [[ -d "${APP_STG_PATH}" ]]; then
              cd $APP_STG_PATH
              sudo docker compose down pacmusic-stg
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL $APP_STG_PATH
              cd $APP_STG_PATH
            fi
            
            # Generate .env file
            echo "APP_STG_PORT=$APP_STG_PORT" > .env
            echo "MINIO_STG_ENDPOINT=$MINIO_STG_ENDPOINT" >> .env
            echo "MINIO_STG_ACCESS_KEY=$MINIO_STG_ACCESS_KEY" >> .env
            echo "MINIO_STG_SECRET_KEY=$MINIO_STG_SECRET_KEY" >> .env
            
            # Run App
            sudo docker compose up --build --detach pacmusic-stg

      - name: Test Deployment
        run: |
          sleep 20
          curl ${{ secrets.STG_URL }}
