name: Deploy Staging 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login ke Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Jalankan Deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          debug: true
          script: |
            set -e  # Stop script jika terjadi error
            
            echo "➡️  Cek apakah folder staging sudah ada..."
            if [ -d "${{ vars.APP_STG_PATH }}" ]; then
              cd ${{ vars.APP_STG_PATH }}
              echo "📌  Masuk ke direktori staging: ${{ vars.APP_STG_PATH }}"

              echo "🔄  Checkout branch main..."
              git checkout main
              git fetch --all
              git pull origin main
            else
              echo "🚀  Folder belum ada, melakukan clone repository..."
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} ${{ vars.APP_STG_PATH }}
              cd ${{ vars.APP_STG_PATH }}
            fi

            echo "🛠  Generate file .env"
            cat <<EOF > .env
            APP_STG_PORT=${{ secrets.APP_STG_PORT }}
            MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}
            MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}
            MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}
            EOF

            echo "📦  Menjalankan ulang container Docker..."
            sudo docker compose down pacmusic-stg
            sudo docker compose up --build --detach pacmusic-stg

      - name: Test Hit Endpoint
        run: |
          echo "⏳  Menunggu 10 detik sebelum test endpoint..."
          sleep 10
          curl -v "${{ secrets.STG_URL }}"
