name: Deploy Staging 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      # 1️⃣ Ambil kode terbaru dari repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Login ke server menggunakan SSH dan jalankan deployment
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            # Cek apakah folder aplikasi sudah ada
            if [ -d "${{ vars.APP_STG_PATH }}" ]; then
              echo "Masuk ke folder aplikasi..."
              cd ${{ vars.APP_STG_PATH }}
              sudo docker compose down pacmusic-stg  # Matikan container lama
              git pull origin main  # Tarik kode terbaru
            else
              echo "Folder tidak ditemukan, cloning repository..."
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} ${{ vars.APP_STG_PATH }}
              cd ${{ vars.APP_STG_PATH }}
            fi

            # Buat file .env baru
            echo "Membuat file .env..."
            echo "APP_STG_PORT=${{ secrets.APP_STG_PORT }}" > .env
            echo "MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}" >> .env
            echo "MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}" >> .env
            echo "MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}" >> .env

            # Login ke Docker Hub
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Jalankan ulang aplikasi dengan versi terbaru
            sudo docker compose up --build --detach pacmusic-stg

      # 3️⃣ Tes apakah aplikasi berjalan dengan baik
      - name: Test Application Endpoint
        run: |
          echo "Menguji endpoint aplikasi..."
          curl -fsSL ${{ secrets.APP_STG_URL }} && echo "✅ Aplikasi Berjalan!" || (echo "❌ Endpoint Gagal!" && exit 1)
