name: Dev Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Testing
    runs-on: ubuntu-latest
    environment: dev-testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env File
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" >> .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env

      - name: Build and Run Container
        run: sudo docker compose up pacmusic-dev --build --detach 

      - name: Test Hit Endpoint
        run: |
          sleep 10
          curl http://localhost:5000
